name: example1_teensy

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'test/**'
      - 'extras/**'
      - '.github/workflows/ubuntu_x64_cmake.yml'
    branches-ignore:    
      - 'feature/next'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        repository: PaulStoffregen/cores.git
        path: deps/cores
        fetch-depth: 1
        ref: master

    - uses: actions/checkout@v2
      with:
        repository: newdigate/teensy-variable-playback
        path: deps/teensy-variable-playback

    - uses: actions/checkout@v2
      with:
        repository: PaulStoffregen/Audio.git
        path: deps/Audio
        ref: master

    - uses: actions/checkout@v2
      with:
        repository: PaulStoffregen/SerialFlash
        path: deps/SerialFlash
        ref: master

    - uses: actions/checkout@v2
      with:
        repository: PaulStoffregen/USBHost_t36
        path: deps/USBHost_t36
        ref: master

    - uses: actions/checkout@v2
      with:
        repository: PaulStoffregen/ST7735_t3
        path: deps/ST7735_t3
        ref: master

    - uses: actions/checkout@v2
      with:
        repository: PaulStoffregen/Wire
        path: deps/Wire
        fetch-depth: 1
        ref: master

    - uses: actions/checkout@v2
      with:
        repository: PaulStoffregen/SD.git
        path: deps/SD
        fetch-depth: 1
        ref: Juse_Use_SdFat

    - uses: actions/checkout@v2
      with:
        repository: PaulStoffregen/arm_math.git
        path: deps/arm_math
        ref: master

    - uses: actions/checkout@v2
      with:
        repository: greiman/SdFat.git
        path: deps/SdFat
        fetch-depth: 1
        ref: master

    - uses: actions/checkout@v2
      with:
        repository: PaulStoffregen/SPI.git
        path: deps/SPI
        fetch-depth: 1
        ref: master

    - uses: actions/checkout@v2
      with:
        repository: PaulStoffregen/Encoder.git
        path: deps/Encoder
        ref: master

    - name: download toolchain
      run: |
        curl  -L "https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2?rev=78196d3461ba4c9089a67b5f33edf82a&hash=D484B37FF37D6FC3597EBE2877FB666A41D5253B" --output /tmp/gcc-arm-none-eabi.tar.bz2
        mkdir -p /opt
        cd /opt
        tar xjf /tmp/gcc-arm-none-eabi.tar.bz2
        rm /tmp/gcc-arm-none-eabi.tar.bz2
        ls

    - name: build
      run: mkdir cmake-build-debug && cd cmake-build-debug && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE:FILEPATH="cmake/toolchains/teensy41.cmake" .. && make