name: extras1_linux

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'examples/**'
      - '.github/workflows/lib_teensy.yml'
    branches-ignore:    
    - 'feature/next'
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: newdigate/teensy-x86-stubs
          path: teensy-x86-stubs

      - uses: actions/checkout@v2
        with:
          repository: newdigate/teensy-x86-sd-stubs
          path: teensy-x86-sd-stubs

      - uses: actions/checkout@v2
        with:
          repository: newdigate/teensy-x86-midi-stubs
          path: teensy-x86-midi-stubs

      - uses: actions/checkout@v2
        with:
          repository: newdigate/teensy-audio-x86-stubs
          path: teensy-audio-x86-stubs

      - uses: actions/checkout@v2
        with:
          repository: newdigate/teensy-audio-x86-stubs
          path: teensy-audio-x86-stubs

      - name: download dependencies
        run: sudo apt-get update && sudo apt-get install -yq libglfw3 libglfw3-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev libx11-dev libxmu-dev libxi-dev libgl-dev libglew-dev libboost-test-dev

      - name: Make and Install teensy-x86-stubs
        run: cd teensy-x86-stubs && mkdir cmake-build-$BUILD_TYPE && cd cmake-build-$BUILD_TYPE && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && sudo make install

      - name: Make and Install teensy-x86-sd-stubs
        run:  cd teensy-x86-sd-stubs && mkdir cmake-build-$BUILD_TYPE && cd cmake-build-$BUILD_TYPE && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && sudo make install          
  
      - name: Make and Install teensy-x86-midi-stubs
        run:  cd teensy-x86-midi-stubs && mkdir cmake-build-$BUILD_TYPE && cd cmake-build-$BUILD_TYPE && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && sudo make install          
  
      - name: Make and Install teensy-audio-x86-stubs
        run:  cd teensy-audio-x86-stubs && mkdir cmake-build-$BUILD_TYPE && cd cmake-build-$BUILD_TYPE && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && sudo make install          

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE      