name: lib_teensy

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'test/**'
      - 'extras/**'
      - '.github/workflows/lib_linux.yml'
    branches-ignore:    
    - 'feature/next'
env:
  BUILD_TYPE: Release
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: download toolchain
      run: |
        curl  -L "https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2?rev=78196d3461ba4c9089a67b5f33edf82a&hash=D484B37FF37D6FC3597EBE2877FB666A41D5253B" --output /tmp/gcc-arm-none-eabi.tar.bz2
        mkdir -p /opt
        cd /opt
        tar xjf /tmp/gcc-arm-none-eabi.tar.bz2
        rm /tmp/gcc-arm-none-eabi.tar.bz2
        ls

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE:FILEPATH="cmake/toolchains/teensy41.cmake"

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE